services:
  wordpress:
    image: wordpress:latest
    platform: linux/amd64
    ports:
      - "8080:80"
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ""  # ไม่มีรหัสผ่าน
      WORDPRESS_DB_NAME: exampledb

  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # อนุญาตให้ไม่มีรหัสผ่าน
      MYSQL_DATABASE: exampledb
